stages:
- name: build jar
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: mvn clean package
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: swydesky/demo:v021501
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
